on:
  push:
    branches:
      - master
      
name: ğŸ› ï¸ Staging deploy on merge
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: cluster.hostliner.cz
        username: ${{ secrets.FTP_USERNAME_CLUSTER }}
        password: ${{ secrets.FTP_PASSWORD_CLUSTER }}
        protocol: ftps
        port: 21
        local-dir: ./output/staging/
        server-dir: czechvisual.space/sluno/newsletter/staging/
        state-name: .staging.json
